# fly.toml app configuration file for frontend deployment
app = 'calimed-frontend'
primary_region = 'fra'

[build]
  dockerfile = "Dockerfile.frontend"
  [build.args]
    VITE_API_URL = "https://calimed-backend.fly.dev"

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.http_checks]]
    interval = "10s"
    grace_period = "30s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = "2s"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/usr/share/nginx/html'
  url_prefix = '/'